name: tokenizer

services:
  smart-contract-service:
    container_name: smart-contract-service
    restart: on-failure
    volumes:
      - ./deployment/test:/usr/src/app/test
      - ./code:/usr/src/app/code
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY:?}
      FUJI_CHAIN_ID: ${FUJI_CHAIN_ID:?}
      FUJI_RPC_URL: ${FUJI_RPC_URL:?}
    build:
        context: ./
        dockerfile: ./deployment/Dockerfile.dev
    expose:
      - 3000
    ports:
      - 8545:8545
    networks:
      - router
  front-end-service:
    container_name: front-end-service
    restart: on-failure
    volumes:
      - ./front/src:/usr/src/app/front/src
    environment:
      SIGNER_PRIVATE_KEY: ${SIGNER_PRIVATE_KEY:?}
      FUJI_CHAIN_ID: ${FUJI_CHAIN_ID:?}
      FUJI_RPC_URL: ${FUJI_RPC_URL:?}
      METAMASK_API_KEY: ${METAMASK_API_KEY:?}
    build:
        context: ./
        dockerfile: ./front/Dockerfile.dev
    expose:
      - 5173
    ports:
      - 5173:5173
    networks:
      - router

networks:
  router:
    driver: bridge